#!/bin/bash
./pps-client-put abc de
./pps-client-put def za
./pps-client-put abd fr
./pps-client-put Cervin Zermatt
./pps-client-put DentBlanche 4357
./pps-client-put Salut Simon
./pps-client-put EPFL Lausanne
./pps-client-put ETH Zurich
./pps-client-put Bulle 1630
./pps-client-put Bern Suisse
./pps-client-put not_a_key not_a_value
./pps-client-put abc xy