#!/bin/bash
./pps-client-put -n 2 -w 2 abc de
./pps-client-put -n 2 -w 2 def za
./pps-client-put -n 2 -w 2 abd fr
./pps-client-put -n 2 -w 2 Cervin Zermatt
./pps-client-put -n 2 -w 2 DentBlanche 4357
./pps-client-put -n 2 -w 2 Salut Simon
./pps-client-put -n 2 -w 2 EPFL Lausanne
./pps-client-put -n 2 -w 2 ETH Zurich
./pps-client-put -n 2 -w 2 Bulle 1630
./pps-client-put -n 2 -w 2 Bern Suisse
./pps-client-put -n 2 -w 2 not_a_key not_a_value
./pps-client-put -n 2 -w 2 abc xy