#!/bin/bash

echo "127.0.0.1 1234" | ./pps-launch-server &
echo "127.0.0.1 1235" | ./pps-launch-server &
echo "127.0.0.1 1236" | ./pps-launch-server &
echo "127.0.0.1 1237" | ./pps-launch-server &
echo "127.0.0.1 1238" | ./pps-launch-server &
echo "127.0.0.1 1239" | ./pps-launch-server &
echo "127.0.0.1 1240" | ./pps-launch-server &
echo "127.0.0.1 1241" | ./pps-launch-server &
echo "127.0.0.1 1242" | ./pps-launch-server &
echo "127.0.0.1 1243" | ./pps-launch-server &
echo "127.0.0.1 1244" | ./pps-launch-server &
echo "127.0.0.1 1245" | ./pps-launch-server &
